### ISSUE TITLE
bubble arrow thing should point to the current cursor position

### ISSUE THREAD

**Issue by wr** [brunchmade/mojito#9] opened 2016-01-01 00:27 UTC
Instead of appearing statically at the bottom center, it should appear as to point at the current cursor position. For example:

<img width="379" alt="screen shot 2015-12-31 at 4 27 33 pm" src="https://cloud.githubusercontent.com/assets/884715/12069282/6a722914-afdb-11e5-8573-15e1d9c7d1c9.png">

**Comment by victorlin** [comment] 2016-01-01 00:53
@wr this is a duplicate of #1

**Comment by wr** [comment] 2016-01-01 00:54
oops ᕕ( ᐛ )ᕗ

**Closed by victorlin** 2016-01-01 00:53 UTC
Labels: bug
